---
name: Markdownlint
description: Lints markdown files.

inputs:
  files:
    description: TODO
    required: false
    default: '**.md'

  path:
    description: TODO
    required: false
    default:  ${{ github.workspace }}

  args:
    description: >
      Additional command-line arguments. TODO
    required: false

runs:
  using: "composite"
  steps:
    - name: Run markdownlint-cli
      shell: bash
      id: run
      run: |
        command_failed=0
        echo "IN"
        echo "command_failed: $command_failed"
        npx markdownlint-cli ${{ inputs.args }} -o result.log -- ${{ inputs.files }} || command_failed=1
        echo "out"
        echo "command_failed: $command_failed"
        ls -la
        echo "::set-output name=full::test"
      working-directory: ${{ inputs.path }}

branding:
  icon:  check-circle
  color: red