---
name: Markdownlint
description: Lints markdown files.

inputs:
  files:
    description: TODO
    required: false

  path:
    description: TODO
    required: false
    default:  ${{ github.workspace }}

  args:
    description: >
      Additional command-line arguments. TODO
    required: false

runs:
  using: "composite"
  steps:
    - name: Install markdownlint-cli
      shell: bash
      run: |
          echo "##[group]Install markdownlint-cli"

          echo "##[command]markdownlint-cli --version"

          npx markdownlint-cli --version

          echo "##[endgroup]"
      
    - name: Run markdownlint-cli
      shell: bash
      id: run
      run: |
        npx markdownlint-cli ${{ inputs.args }} -- ${{ inputs.files }}
      working-directory: ${{ inputs.path }}

branding:
  icon:  check-circle
  color: red