---
name: Action tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run action
        id: action
        uses: tomtomsen/markdown-lint-github-action@main
        with:
          files: ${{ github.workspace }}/tests/**.md
        continue-on-error: true

      - name: 'contains ::warning'
        run: |
          echo "${{ steps.action.outputs.full }}"
          echo "${{ steps.action.outputs.full }}" | grep "::warning"

      